<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="nsdldepnb658" failures="1" tests="8" name="Listeners_program" time="0.095" errors="0" timestamp="2024-07-15T13:24:36 IST">
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod1" time="0.0"/>
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10]
at custodian.ItestListenerWithExample.testMethod2(ItestListenerWithExample.java:23)
at java.base/java.util.ArrayList.forEach(Unknown Source)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod3" time="0.006">
    <skipped/>
  </testcase> <!-- testMethod3 -->
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod4" time="0.0"/>
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod4" time="0.0"/>
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod4" time="0.002"/>
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod4" time="0.0"/>
  <testcase classname="custodian.ItestListenerWithExample" name="testMethod4" time="0.0"/>
</testsuite> <!-- Listeners_program -->
